---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-amf-config
  labels:
    epc-mode: amf
data:
  amf.yaml: |
    logger:
        file: /var/log/open5gs/amf.log
        #level: debug
        #domain: sbi

    amf:
        sbi:
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-amf
        ngap:
          dev: {{ .Values.k8s.interface }}
        guami:
          - plmn_id:
              mcc: {{ .Values.config.mcc }}
              mnc: {{ .Values.config.mnc }}
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: {{ .Values.config.mcc }}
              mnc: {{ .Values.config.mnc }}
            tac: {{ .Values.config.tac }}
        plmn_support:
        - plmn_id:
            mcc: {{ .Values.config.mcc }}
            mnc: {{ .Values.config.mnc }}
          s_nssai:
          - sst: 1
            sd: 1
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf0

    nrf:
     sbi:
       name: {{ .Release.Name }}-nrf

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-amf
  labels:
    epc-mode: amf
    pool: {{ .Values.config.open5gsLbPool }}
spec:
  selector:
    epc-mode: amf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9080   
      targetPort: 80
  
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-amf-deployment
  labels:
    epc-mode: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata: 
      labels:
        epc-mode: amf
    spec:    
      containers:
        - name: amf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-amfd", "-c", "/open5gs/config-map/amf.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: {{ .Release.Name }}-amf-config
          configMap:
            name: {{ .Release.Name }}-amf-config
