---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-k8s-wait-for
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-k8s-wait-for
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-k8s-wait-for
  apiGroup: rbac.authorization.k8s.io  

---
apiVersion: v1
kind: ServiceAccount
metadata:  
  name: {{ .Release.Name }}-k8s-wait-for
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-k8s-wait-for
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]  