---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pcf-config
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log
    
    db_uri: mongodb://{{ .Release.Name }}-mongodb-svc/{{ .Values.db.name }}    

    pcf:
      sbi:     
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-pcf
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pcf
  labels:
    epc-mode: pcf
spec:
  selector:
    epc-mode: pcf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
      
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pcf-deployment
  labels:
    epc-mode: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcf
  template:
    metadata:
      labels:
        epc-mode: pcf
    spec:    
      containers:
        - name: pcf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-pcfd", "-c", "/open5gs/config-map/pcf.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-pcf-config
            mountPath: /open5gs/config-map/pcf.yaml
            subPath: "pcf.yaml"          
      volumes:
        - name: {{ .Release.Name }}-pcf-config
          configMap:
            name: {{ .Release.Name }}-pcf-config         
