---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    logger:
        file: /var/log/open5gs/udm.log

    udm:
      sbi:   
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-udm
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-udm
  labels:
    epc-mode: udm
spec:
  selector:
    epc-mode: udm
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 80
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udm-deployment
  labels:
    epc-mode: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
    spec:   
      containers:
        - name: udm
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-udmd", "-c", "/open5gs/config-map/udm.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-udm-config
            mountPath: /open5gs/config-map/udm.yaml
            subPath: "udm.yaml"
      volumes:
        - name: {{ .Release.Name }}-udm-config
          configMap:
            name: {{ .Release.Name }}-udm-config
